import { open, readFile } from "node:fs/promises";
import { extname, join } from "node:path";
import fg from "fast-glob";
import ignore from "ignore";

// .gitignore and .pickcheckignore are repo plumbing, like .git/ and
// node_modules/ — never audit-relevant content, so they're force-ignored
// the same way. Every other dotfile is scanned: rules like
// sec/no-env-in-git need to see `.env`.
//
// Unlike DEFAULT_IGNORED below, these are NOT overridable: auditing
// node_modules or .git is never something anyone means to do.
const ALWAYS_IGNORED = [
  "**/.git/**",
  "**/node_modules/**",
  "**/.gitignore",
  "**/.pickcheckignore",
];

/**
 * Build/generated output, ignored by default in gitignore syntax so it
 * matches at any depth (`dist/` catches `apps/web/dist/` too).
 *
 * pickcheck audits *source*; findings from a webpack chunk or a compiled
 * bundle are noise the user can't act on. This has to be a default rather
 * than relying on .gitignore because .gitignore doesn't reliably cover it
 * — see DECISIONS/0023 for the three separate ways a real Next.js app
 * leaked ~45 findings out of .next/ despite having a correct .gitignore.
 *
 * Every entry is overridable: .pickcheckignore is applied last, so a
 * negation there (`!dist/`) re-includes it.
 */
const DEFAULT_IGNORED = [
  // JS/TS framework + bundler output
  ".next/",
  "dist/",
  "build/",
  "out/",
  ".output/",
  ".svelte-kit/",
  ".nuxt/",
  ".turbo/",
  ".vercel/",
  "coverage/",
  // other ecosystems
  "__pycache__/",
  "target/",
  // pickcheck's own output — report.html is generated markup with inline
  // JS that trips our own rules, and history.json is state. Auditing our
  // own artifacts is the same mistake as auditing .next/.
  ".pickcheck/",
  // bundled/minified single files that live outside those directories
  "*.min.js",
  "*.min.css",
  "*.bundle.js",
];

/**
 * Extensions worth content-sniffing for generated code. Restricted to
 * code-ish files because a long line is normal in .md (a URL), .json, or
 * .svg and says nothing about whether a human wrote it.
 */
const SNIFFABLE_EXTENSIONS = new Set([
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".ts",
  ".tsx",
  ".css",
  ".scss",
]);

/**
 * Mean line length above which a file reads as machine-generated.
 *
 * Deliberately the *average*, not the longest line. A single very long
 * line is normal in hand-written code — an inline SVG `<path d="...">`, a
 * base64 data URI, a long Tailwind class string. Measured on real corpus
 * source, `taxonomy`'s `app/api/og/route.tsx` has a 1,664-character line
 * (an inline SVG logo) inside a perfectly ordinary 148-line file, and a
 * max-line-length rule silently dropped it — hiding two genuine findings.
 * See DECISIONS/0023.
 *
 * Averages separate the two cleanly: real corpus source measures 32-50
 * chars/line even when its longest line is 1,664, while minified output
 * has few lines of many thousands each. 500 sits an order of magnitude
 * above observed source and well below any bundle.
 *
 * The asymmetry matters when picking this: auditing one extra file is
 * mild noise, but silently skipping real source hides real bugs — so this
 * errs toward keeping files.
 */
const GENERATED_MEAN_LINE_LENGTH = 500;

/** Only the head of a file is read to classify it — bundles are huge and we need one long line, not all of them. */
const SNIFF_BYTES = 64 * 1024;

/** Concurrency cap for content sniffing, so a big repo can't exhaust file descriptors. */
const SNIFF_CONCURRENCY = 64;

export interface ScanOptions {
  /** Repo root to scan. */
  cwd: string;
}

/**
 * Lists every source file in the repo: everything except .git,
 * node_modules, the ignore files themselves, DEFAULT_IGNORED build output,
 * anything .gitignore or .pickcheckignore excludes, and anything that
 * looks generated by content (see isGeneratedContent).
 *
 * Precedence is gitignore's own: defaults first, then .gitignore, then
 * .pickcheckignore — so the user's file has the last word and can negate
 * a default with `!`. Returned paths are relative to `cwd`,
 * POSIX-separated, and sorted for deterministic output.
 */
export async function scanRepo({ cwd }: ScanOptions): Promise<string[]> {
  const [gitignore, pickcheckignore] = await Promise.all([
    readIgnoreFile(cwd, ".gitignore"),
    readIgnoreFile(cwd, ".pickcheckignore"),
  ]);

  const filter = ignore().add(DEFAULT_IGNORED).add(gitignore).add(pickcheckignore);

  const files = await fg("**/*", {
    cwd,
    dot: true,
    onlyFiles: true,
    // Excluding the big generated directories at the walk level (rather
    // than filtering after) is what keeps a 10k-file .next/ from
    // dominating scan time — but only for defaults the user hasn't
    // negated, since fast-glob's ignore can't be un-ignored later.
    ignore: [...ALWAYS_IGNORED, ...globIgnoresFor(pickcheckignore)],
  });

  const candidates = files.filter((file) => !filter.ignores(file)).sort();
  return dropGeneratedFiles(cwd, candidates);
}

/**
 * DEFAULT_IGNORED as fast-glob patterns, minus any the user re-included
 * in .pickcheckignore. `ignore`'s own matcher decides what counts as
 * re-included, so `!dist/`, `!dist/**` and friends all work without this
 * having to parse gitignore syntax itself.
 *
 * The probe applies the default *and then* the user's file, and asks
 * whether a representative path still ends up ignored. Testing the user's
 * patterns alone doesn't work: `ignore` only reports `unignored: true`
 * when a negation overrides a rule in the same filter, so a lone
 * `!dist/` — with no `dist/` preceding it — reports nothing at all.
 */
function globIgnoresFor(pickcheckignore: string): string[] {
  return DEFAULT_IGNORED.filter((pattern) => {
    const probe = pattern.endsWith("/")
      ? `${pattern}probe`
      : pattern.replace("*", "probe");
    return ignore().add(pattern).add(pickcheckignore).ignores(probe);
  }).map((pattern) =>
    pattern.endsWith("/") ? `**/${pattern.slice(0, -1)}/**` : `**/${pattern}`,
  );
}

/**
 * Drops files whose *content* says they're generated, catching bundlers
 * DEFAULT_IGNORED doesn't know about (the list can only ever name the
 * tools we've heard of). Read errors are non-fatal: a file we can't
 * classify is kept and left for the tiers to deal with, matching the
 * "never crash the audit" contract everywhere else.
 */
async function dropGeneratedFiles(cwd: string, files: string[]): Promise<string[]> {
  const kept: string[] = [];

  for (let i = 0; i < files.length; i += SNIFF_CONCURRENCY) {
    const batch = files.slice(i, i + SNIFF_CONCURRENCY);
    const verdicts = await Promise.all(
      batch.map(async (file) => {
        if (!SNIFFABLE_EXTENSIONS.has(extname(file).toLowerCase())) {
          return false;
        }
        return isGeneratedContent(join(cwd, file));
      }),
    );
    batch.forEach((file, index) => {
      if (!verdicts[index]) {
        kept.push(file);
      }
    });
  }

  return kept;
}

/** True if the head of this file looks like bundler output rather than hand-written source. */
async function isGeneratedContent(absolutePath: string): Promise<boolean> {
  let head: string;
  try {
    const handle = await open(absolutePath, "r");
    try {
      const buffer = Buffer.alloc(SNIFF_BYTES);
      const { bytesRead } = await handle.read(buffer, 0, SNIFF_BYTES, 0);
      head = buffer.subarray(0, bytesRead).toString("utf-8");
    } finally {
      await handle.close();
    }
  } catch {
    return false;
  }

  // A source-map reference is emitted by build tooling, not typed by hand.
  if (/^[/*]{2,3}#\s*sourceMappingURL=/m.test(head)) {
    return true;
  }

  // Mean line length over the head. Measuring the average rather than the
  // longest line is what keeps hand-written files with one giant SVG path
  // or data URI in the audit — see GENERATED_MEAN_LINE_LENGTH.
  const lines = head.split("\n");
  if (lines.length === 0) {
    return false;
  }
  const meanLineLength = head.length / lines.length;
  return meanLineLength >= GENERATED_MEAN_LINE_LENGTH;
}

async function readIgnoreFile(cwd: string, name: string): Promise<string> {
  try {
    return await readFile(join(cwd, name), "utf-8");
  } catch (error) {
    if (isErrnoException(error) && error.code === "ENOENT") {
      return "";
    }
    throw error;
  }
}

function isErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
